import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.9"

    const val com_squareup_retrofit2: String = "2.9.0"

    const val androidx_databinding: String = "4.0.1"

    const val org_jetbrains_kotlin: String = "1.4.0"

    const val androidx_navigation: String = "2.3.0"

    const val androidx_lifecycle: String = "2.2.0"

    const val androidx_room: String = "2.2.5"

    const val com_android_tools_build_gradle: String = "4.0.1"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val junit_junit: String = "4.13"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val koin_androidx_viewmodel: String = "2.1.6"

    const val weather_icons_typeface: String = "2.0.10.5"

    const val logging_interceptor: String = "4.8.1"

    const val constraintlayout: String = "2.0.0-rc1"

    const val work_runtime_ktx: String = "2.4.0"

    const val espresso_core: String = "3.2.0"

    const val iconics_views: String = "5.0.3"

    const val moshi_kotlin: String = "1.9.3"

    const val lint_gradle: String = "27.0.1"

    const val appcompat: String = "1.2.0"

    const val liveevent: String = "1.2.0"

    const val core_ktx: String = "1.3.1"

    const val material: String = "1.2.0"

    const val aapt2: String = "4.0.1-6197926"

    const val coil: String = "0.11.0"

    /**
     * Current version: "6.1.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
